### ISSUE TITLE
Implementation details about locks

### ISSUE THREAD

**Issue by leonfs** [Nordstrom/kubernetes-vulcand-router#1]
Hi,

I've been reviewing the kubernetes-vulcand-router (and kube2sky) code. It called my attention the lock used when accessing the information from headless services. What's the reason behind the lock? I couldn't find any information on kubernetes code, neither on kube2sky. 

Thanks, and great work. I've been working on an vulcand to k8s adapter as well. But I run into some problems when accessing the Master API over SSL. That's when looking for a solution I found this repo.

**Comment by emmanuel** [comment]
Hi,

You are referring to [this `sync.Mutex` from `kube2sky`](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/kube2sky/kube2sky.go#L91) (and [this one from `kubernetes-vulcand-router`](https://github.com/Nordstrom/kubernetes-vulcand-router/blob/2ac546b1e830687dad63dfcaa42c3fc17d7ac996/relay.go#L75), correct?

I'll be honest, I'm not exactly sure why it's there. I believe the purpose is to protect against non-determinism, by limiting the process to one update per object (reducing concurrency). This is necessary because the client is reading from a remote source (the kubernetes API), and then updating etcd based on that; if multiple updates were occurring concurrently, then you would eventually encounter a scenario where concurrent overlapping reads and writes would interleave in ways that produce invalid results. 

Now that you raise the question, it occurs to me that using [etcd CAS (compare-and-swap) features](https://coreos.com/etcd/docs/latest/api.html#atomic-compare-and-swap) to implement optimistic concurrency control–instead of the pessimistic concurrency control in place today (`sync.Mutex`)–might be a more robust strategy.

**Comment by leonfs** [comment]
Hi Emmanuel, 

True, etcd CAS sounds like a better idea. But that would work only for kube2sky as communicates directly to ETCD . 

But the router is communicating directly to Vulcand API. I inspected the code very quickly and it seems they are using mutexes internally.

**Comment by emmanuel** [comment]
@leonfs - thanks for the discussion. I'm going to close the issue. Feel free to re-open or continue to use it for discussion.
